package com.tjliqy.model.baseModel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEquipment<M extends BaseEquipment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public void setPlate(java.lang.String plate) {
		set("plate", plate);
	}

	public java.lang.String getPlate() {
		return get("plate");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setModel(java.lang.String model) {
		set("model", model);
	}

	public java.lang.String getModel() {
		return get("model");
	}

	public void setSpecifications(java.lang.String specifications) {
		set("specifications", specifications);
	}

	public java.lang.String getSpecifications() {
		return get("specifications");
	}

	public void setEngine(java.lang.String engine) {
		set("engine", engine);
	}

	public java.lang.String getEngine() {
		return get("engine");
	}

	public void setChassis(java.lang.String chassis) {
		set("chassis", chassis);
	}

	public java.lang.String getChassis() {
		return get("chassis");
	}

	public void setProduct(java.lang.String product) {
		set("product", product);
	}

	public java.lang.String getProduct() {
		return get("product");
	}

	public void setSituation(java.lang.String situation) {
		set("situation", situation);
	}

	public java.lang.String getSituation() {
		return get("situation");
	}

	public void setManufacturer(java.lang.String manufacturer) {
		set("manufacturer", manufacturer);
	}

	public java.lang.String getManufacturer() {
		return get("manufacturer");
	}

	public void setOriginalValue(java.lang.Integer originalValue) {
		set("original_value", originalValue);
	}

	public java.lang.Integer getOriginalValue() {
		return get("original_value");
	}

	public void setDepreciation(java.lang.Integer depreciation) {
		set("depreciation", depreciation);
	}

	public java.lang.Integer getDepreciation() {
		return get("depreciation");
	}

	public void setDepreciationAge(java.lang.Integer depreciationAge) {
		set("depreciation_age", depreciationAge);
	}

	public java.lang.Integer getDepreciationAge() {
		return get("depreciation_age");
	}

	public void setPurchaseTime(java.util.Date purchaseTime) {
		set("purchase_time", purchaseTime);
	}

	public java.util.Date getPurchaseTime() {
		return get("purchase_time");
	}

}
