package com.tjliqy.model.baseModel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setGoodId(java.lang.Integer goodId) {
		set("good_id", goodId);
	}

	public java.lang.Integer getGoodId() {
		return get("good_id");
	}

	public void setCost(java.math.BigDecimal cost) {
		set("cost", cost);
	}

	public java.math.BigDecimal getCost() {
		return get("cost");
	}

	public void setTotalCost(java.math.BigDecimal totalCost) {
		set("total_cost", totalCost);
	}

	public java.math.BigDecimal getTotalCost() {
		return get("total_cost");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setNum(java.lang.Long num) {
		set("num", num);
	}

	public java.lang.Long getNum() {
		return get("num");
	}

}
