package com.tjliqy.model.baseModel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFood<M extends BaseFood<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setShelfLife(java.util.Date shelfLife) {
		set("shelf_life", shelfLife);
	}

	public java.util.Date getShelfLife() {
		return get("shelf_life");
	}

	public void setOrigin(java.lang.String origin) {
		set("origin", origin);
	}

	public java.lang.String getOrigin() {
		return get("origin");
	}

}
