package com.tjliqy.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("equipment", "id", Equipment.class);
		arp.addMapping("goods", "id", Goods.class);
		arp.addMapping("log", "id", Log.class);
		arp.addMapping("user", "id", User.class);
	}
}

