package com.tjliqy.model;

import com.tjliqy.model.baseModel.BaseBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Brand extends BaseBrand<Brand> {
	public static final Brand dao = new Brand().dao();
}
