package com.tjliqy.model;

import com.tjliqy.model.baseModel.BaseClothes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Clothes extends BaseClothes<Clothes> {
	public static final Clothes dao = new Clothes().dao();
}
