package com.tjliqy.model;

import com.tjliqy.model.baseModel.BaseEquipment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Equipment extends BaseEquipment<Equipment> {
	public static final Equipment dao = new Equipment().dao();
}
