package com.tjliqy.model;

import com.tjliqy.model.baseModel.BaseFood;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Food extends BaseFood<Food> {
	public static final Food dao = new Food().dao();
}
