package com.tjliqy.model;

import com.tjliqy.model.baseModel.BaseGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods().dao();
}
